name: "PAL Consumer Tape"
description: "PAL Consumer VHS tape with separate YC output and VITC timecodes"

output:
  filename: "example-output/pal-consumer-tape"
  format: "pal-yc"

pipeline:
  preprocessing:
    filters:
      chroma:
        enabled: true
  
  metadata:
    generators:
      - type: "vitc"
        enabled: true
        lines: [15, 16, 17, 18, 19, 20, 328, 329, 330, 331, 332, 333]
        start_frame_offset: 0
      
      - type: "color-burst"
        enabled: true

sections:
  - name: "Lead-in"
    duration: 1
    source:
      type: "yuv422-image"
      file: "testcard-images/pal-raw/625_50_75_BARS.raw"
  
  - name: "Test Content"
    duration: 20
    source:
      type: "yuv422-image"
      file: "testcard-images/pal-raw/625_50_75_BARS.raw"
  
  - name: "Lead-out"
    duration: 1
    source:
      type: "yuv422-image"
      file: "testcard-images/pal-raw/625_50_75_BARS.raw"
